### ISSUE TITLE
Logging missing

### ISSUE THREAD

**Issue by ma-ke-le** [mindmill/ladon-s3-server#1]
For our testing purpose we need to activate logging, so we can see what the s3 server is doinig.

**Comment by ulrichsralf** [comment]
Thanks for your feedback, there currently two logging options: 
1. PerformanceLoggingFilter is a servlet filter that logs every request and duration in ms.
2. LoggingRepository is a delegate repository that logs every call on the actual S3Repository

Have a look at the [BeanConfig](https://github.com/mindmill/ladon-s3-server/blob/master/ladon-s3-server-boot/src/main/java/de/mc/ladon/s3server/config/BeanConfig.java)  for an example how to use them. 
Cheers 
Ralf
