### ISSUE TITLE
Clarify license : Free for private use, easy commercial licensing available

### ISSUE THREAD

**Issue by yhilem** [mindmill/ladon-s3-server#4]
Hi,
Is  internal deployment in my company is considered private use?
Thanks
Youcef HILEM

**Comment by ulrichsralf** [comment]
Hi Youcef,
unfortunately any usage in a company is considered commercial, but don't worry, as I wrote, licensing is easy. Please email me a little about your company and your usecase at ralf.ulrich@mind-consulting.de
I'm sure we can find a solution where you can benefit from commercial support as well.
Cheers
Ralf from MC
