### ISSUE TITLE
s3 browser cannot connect

### ISSUE THREAD

**Issue by mrkk** [mindmill/ladon-s3-server#5]
not sure what the user password should be

I built it locally using maven and ran server

then tried to connect s3 browser, but I cannot

**Comment by ulrichsralf** [comment]
Default security is configured here:
https://github.com/mindmill/ladon-s3-server/blob/master/ladon-s3-server-boot/src/main/resources/application.properties#L12

Have a look at 
https://github.com/mindmill/ladon-s3-server/blob/master/ladon-s3-server-fs/src/main/java/de/mc/ladon/s3server/repository/impl/FSRepository.java#L469
Keep in mind the provided FSRepository is just a starting point to implement your Custom Respository!

With securityEnabled=false you should be able to use "SYSTEM" / "SYSTEM"
